### ISSUE TITLE
CSAF `icsa-24-312-01` has an incorrect sha512 checksum

### ISSUE THREAD

**Issue by mgoetzegb** [cisagov/CSAF#142]
# 🐛 Summary #

CSAF `icsa-24-312-01` has an incorrect sha512 checksum.

File: https://github.com/cisagov/CSAF/blob/develop/csaf_files/OT/white/2024/icsa-24-312-01.json
Checksum: https://github.com/cisagov/CSAF/blob/develop/csaf_files/OT/white/2024/icsa-24-312-01.json.sha512

## To reproduce ##

Execute in a bash (like) shell:
```sh
wget https://raw.githubusercontent.com/cisagov/CSAF/develop/csaf_files/OT/white/2024/icsa-24-312-01.json
wget https://raw.githubusercontent.com/cisagov/CSAF/develop/csaf_files/OT/white/2024/icsa-24-312-01.json.sha512
sha512sum -c icsa-24-312-01.json.sha512
```

## Expected behavior ##

Expected signature check to succeed, but it failed.

## Any helpful log output or screenshots ##

Output of command above:

```console
icsa-24-312-01.json: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
```

**Comment by mstrad** [comment]
Fixed in this PR https://github.com/cisagov/CSAF/pull/143

Thank you for reporting this issue @mgoetzegb .
