### ISSUE TITLE
Advisories prior to 2017

### ISSUE THREAD

**Issue by ZenW00kie** [cisagov/CSAF#39]
# 💡 Summary #

Publishing advisories that were issued prior to 2017.

## Motivation and context ##

My research group is investigating trends for ICS/ICSM advisories and we are trying to look at differences between ICS-CERT advisories and what manufacturers are posting as well as the differences in scoring between the CVEs that are included in the advisories across a variety of sources (NVD, ICS-CERT etc). 

As part of this, we want to look at as much data as possible, and we love the CSAF data you all have for more recent advisories. So we were wondering if there's a plan to backfill prior advisories (and if not, maybe we can do it and create a pull request with the data).

**Comment by Daniel-CISA-CVD** [comment]
@ZenW00kie Attempts have been made to do this but we decided to focus our efforts elsewhere due to the data formatting inconsistencies of pre 2017 advisories.
