### ISSUE TITLE
Umlaut 'ä' wrong in the raw data

### ISSUE THREAD

**Issue by Crubumble** [cisagov/CSAF#77]
https://github.com/cisagov/CSAF/blob/e734e2c37bd0fd268b06c18fcee7797adf3e71c1/csaf_files/OT/white/2019/icsma-19-022-01.json#L192

Should be **Dräger** like in the rest of the document

**Comment by mstrad** [comment]
Resolved in most recent commit. Thank you for bringing this to our attention!
