### ISSUE TITLE
invalid hash and missing file

### ISSUE THREAD

**Issue by kalidor** [cisagov/CSAF#79]
# 🐛 Summary #

It seems there is some file with the wrong signature:
- `csaf_files/OT/white/2024/icsa-24-037-02.json`,
- `csaf_files/OT/white/2024/icsa-24-037-01.json`,
- `csaf_files/OT/white/2021/icsa-21-250-01.json`.

And one file seems missing. It is present in the index file (`csaf_files/OT/white/index.txt`)
- `csaf_files/OT/white/2024/icsa-24-156-01.json`

## To reproduce ##

- pull the repo
- use same script used in this previous issues https://github.com/cisagov/CSAF/issues/28, can be used.

## Expected behavior ##

- only right signature
- no missing files

**Comment by mstrad** [comment]
Resolved in most recent commit. Thank you for bringing this to our attention!
